# Generated by Django 5.2.4 on 2025-08-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(help_text='Nombre de la institución educativa', max_length=100)),
                ('titulo', models.CharField(help_text='Título obtenido', max_length=100)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de estudios')),
                ('fecha_fin', models.DateField(help_text='Fecha de finalización de estudios')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(help_text='Nombre del cargo desempeñado', max_length=100)),
                ('empresa', models.CharField(help_text='Nombre de la empresa', max_length=100)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio')),
                ('fecha_fin', models.DateField(help_text='Fecha de finalización')),
                ('descripcion', models.TextField(help_text='Descripción de las funciones')),
            ],
        ),
        migrations.CreateModel(
            name='Hobbie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del hobbie o pasatiempo', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción breve (opcional)')),
            ],
        ),
    ]
